// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadModel(arg1, arg2) {
  return window['go']['main']['App']['DownloadModel'](arg1, arg2);
}

export function GenerateSubtitles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateSubtitles'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}
