// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

<<<<<<< HEAD
export function DeleteModel(arg1:string):Promise<void>;

export function DownloadModel(arg1:string):Promise<string>;

export function GenerateSubtitles(arg1:context.Context,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetActiveModel():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListModels():Promise<Array<Record<string, any>>>;

export function SetActiveModel(arg1:string):Promise<void>;
=======
export function DownloadModel(arg1:context.Context,arg2:string):Promise<string>;

export function GenerateSubtitles(arg1:context.Context,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListModels():Promise<Array<Record<string, any>>>;
>>>>>>> 1c16b9c57654212a0011165ba3c6458c1639bb75
