// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function DeleteModel(arg1:string):Promise<void>;

export function DownloadModel(arg1:string):Promise<string>;

export function GenerateSubtitles(arg1:context.Context,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetActiveModel():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListModels():Promise<Array<Record<string, any>>>;

export function SetActiveModel(arg1:string):Promise<void>;
