// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

<<<<<<< HEAD
export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
=======
export function DownloadModel(arg1, arg2) {
  return window['go']['main']['App']['DownloadModel'](arg1, arg2);
>>>>>>> 1c16b9c57654212a0011165ba3c6458c1639bb75
}

export function GenerateSubtitles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateSubtitles'](arg1, arg2, arg3, arg4);
}

<<<<<<< HEAD
export function GetActiveModel() {
  return window['go']['main']['App']['GetActiveModel']();
}

=======
>>>>>>> 1c16b9c57654212a0011165ba3c6458c1639bb75
export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}
<<<<<<< HEAD

export function SetActiveModel(arg1) {
  return window['go']['main']['App']['SetActiveModel'](arg1);
}
=======
>>>>>>> 1c16b9c57654212a0011165ba3c6458c1639bb75
